image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test
  - execute

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

bootRun-services:
  stage: execute
  script:
    gradle authentication-microservice:bootRun cluster-microservice:bootRun request-microservice:bootRun system-tests:bootRun --parallel &
