image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test
  - execute

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-cluster-microservice:
  stage: build
  script:
    gradle cluster-microservice:assemble cluster-microservice:testClasses

checkStyle-cluster-microservice:
  stage: staticAnalysis
  script:
    gradle cluster-microservice:checkstyleMain cluster-microservice:checkStyleTest
  allow_failure: true


PMD-cluster-microservice:
  stage: staticAnalysis
  script:
    gradle cluster-microservice:pmdMain
  allow_failure: true

test-cluster-microservice:
  stage: test
  script:
    - gradle cluster-microservice:test cluster-microservice:jacocoTestReport
    - cat cluster-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?%.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
